version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    labels:
    - "automerge"
    schedule:
      interval: daily
    open-pull-requests-limit: 4
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
